### app/models/__init__.py
from app.models.role import Role
from app.models.user import User
from app.models.hotel import Hotel
from app.models.hotel_image import HotelImage
from app.models.room_type import RoomType
from app.models.room import Room
from app.models.room_image import RoomImage
from app.models.amenity import Amenity
from app.models.hotel_amenity import hotel_amenities
from app.models.room_amenity import room_amenities
from app.models.booking import Booking
from app.models.booking_detail import BookingDetail
from app.models.payment import Payment
from app.models.discount_code import DiscountCode
from app.models.discount_usage import DiscountUsage
from app.models.promotion import Promotion
from app.models.review import Review
from app.models.notification import Notification
from app.models.password_reset import PasswordReset
from app.models.email_verification import EmailVerification
from app.models.cancellation_policy import CancellationPolicy
from app.models.favorite import Favorite
from app.models.search_history import SearchHistory
from app.models.login_history import LoginHistory